[Rule]
# btsow
DOMAIN-SUFFIX,2cnjuh34jbpoint.com,REJECT
DOMAIN-SUFFIX,bnhtml.com,REJECT
DOMAIN-SUFFIX,tellme.pw,REJECT
DOMAIN-SUFFIX,djv99sxoqpv11.cloudfront.net,REJECT
DOMAIN-SUFFIX,increasinglycockroachpolicy.com,REJECT
# btsow
# rardb
DOMAIN-SUFFIX,notifydisparage.com,REJECT
# rardb
# 海盗
DOMAIN-SUFFIX,iconcardinal.com,REJECT
DOMAIN-SUFFIX,js.wpadmngr.com,REJECT
# 海盗
# 猫字幕
DOMAIN-SUFFIX,adnxs.com,REJECT
DOMAIN-SUFFIX,popads.net,REJECT
DOMAIN-SUFFIX,propellerads.com,REJECT  
DOMAIN-SUFFIX,ceetomouwique.net,REJECT
DOMAIN-SUFFIX,phahifoobsie.net,REJECT  
DOMAIN-SUFFIX,aikoxouftuxoun.net,REJECT
DOMAIN-SUFFIX,seefaurerowizoa.net,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,huvathussicka.net,REJECT
DOMAIN-KEYWORD,paizowheefash,REJECT
DOMAIN-SUFFIX,whounaiphie.net,REJECT
DOMAIN-SUFFIX,noaviphesh.net,REJECT  
DOMAIN-SUFFIX,vaufekonaub.net,REJECT  
DOMAIN-SUFFIX,shaissugritit.net,REJECT  
DOMAIN-SUFFIX,glabsuckoupy.net,REJECT
DOMAIN-SUFFIX,sushainsihogner.net,REJECT
DOMAIN-SUFFIX,sapsobughoatch.net,REJECT
DOMAIN-SUFFIX,voawheevie.net,REJECT
DOMAIN-SUFFIX,thoufoophuch.net,REJECT
DOMAIN-SUFFIX,pdxprvxhtna.com,REJECT
# 猫字幕
# 京东极光快手广告屏蔽
DOMAIN-SUFFIX,lf-cdn-tos.bytescm.com,REJECT
DOMAIN-SUFFIX,open.e.kuaishou.com,REJECT
DOMAIN-SUFFIX,tobapplog.ctobsnssdk.com,REJECT
DOMAIN-SUFFIX,mi.gdt.qq.com,REJECT
DOMAIN-SUFFIX,mon.zijieapi.com,REJECT
DOMAIN-SUFFIX,mssdk.volces.com,REJECT
DOMAIN-SUFFIX,im-x.jd.com,REJECT
DOMAIN-SUFFIX,gdfp.gifshow.com,REJECT
DOMAIN-SUFFIX,jpush.io,REJECT
DOMAIN-SUFFIX,jpush.cn,REJECT
# 京东极光快手广告屏蔽
# 头条广告
DOMAIN-SUFFIX,toblog.ctobsnssdk.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT
# 头条广告
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT
DOMAIN-SUFFIX,api-access.pangolin-sdk-toutiao1.com,REJECT
DOMAIN-SUFFIX,tnc3-alisc1.zijieapi.com,REJECT
DOMAIN-SUFFIX,open.e.kuaishou.cn,REJECT
DOMAIN-SUFFIX,*ad.adukwai.com,REJECT
DOMAIN-SUFFIX,v4-lm.adukwai.com,REJECT
DOMAIN-SUFFIX,api.liuliangguo.com,REJECT
DOMAIN-SUFFIX,youxinhuyu.cn,REJECT
DOMAIN-SUFFIX,tnc3-aliec2.zijieapi.com,REJECT
DOMAIN-SUFFIX,tnc3-bjlgy.zijieapi.com,REJECT
# 快手
DOMAIN-SUFFIX,adkwai.com,REJECT
DOMAIN-SUFFIX,adukwai.com,REJECT
